# [ADDR:]service_name		must be in /etc/services, or port number
# socket_type			stream/dgram/raw/rdm/seqpacket
# protocol			tcp/udp
# wait/nowait[.max]		wait is usually for udp, nowait for tcp
#				max: max copies to run
# user[.group] or user[:group]	user and group to run under
# program_path			program to run
# arg0 arg1 arg2 ...		arguments, INCLUDING program name (arg0)

ssh	stream	tcp	nowait	root	/usr/bin/dropbear	dropbear -i -s -g
